### ISSUE TITLE
Confusion in gram matrix normalization division step's denominator values

### ISSUE THREAD

**Issue by RahulBhalley** [leongatys/PytorchNeuralStyleTransfer#14]
In `GramMatrix` class, at 3rd cell and 7th line, shouldn't we divide the gram matrix by the product of channels, height, and width (i.e. `G.div_(c*h*w)` instead of `G.div_(h*w)`)? Or am I missing something? 

Edit: I do notice better results with your gram matrix implementation but not sure how this is a correct normalization. 🤔

**Comment by leongatys** [comment]
The Gram matrix computation only sums over the spatial dimensions (h*w) therefore we only normalize over these dimensions to make the result independent of the spatial size of the image. 

The final loss is independent of the number of channels, because the MSE on the difference between the two Gram matrices normalizes by the number of channels.

If you were to normalize the Gram matrix by the number of channels as you suggest and then compute the MSE, your loss would be dependent on the number of channels, i.e. going to 0 as number of channels go to infinity.

**Comment by RahulBhalley** [comment]
Okay. Thanks for answering.
